[tool.isort]
profile = "black"
split_on_trailing_comma = true

[tool.black]
line-length = 79
skip-string-normalization = true
# see https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#preview-style
preview = true
enable-unstable-feature = ["hug_parens_with_braces_and_square_brackets"]

[tool.pylint]
max-line-length = 80

[tool.coverage.run]
source = ['.']

[tool.coverage.report]
skip_empty = true
include = ['alma_tests_cacher/*']

[tool.pytest.ini_options]
pythonpath = '.'
testpaths = ['tests']
